# Cloudflare Workers (Wrangler) のビルド・テスト実行に必要なパッケージの許可リスト
onlyBuiltDependencies:
  # バンドル
  - esbuild
  # シュミレータ
  - workerd
allowBuilds:
  esbuild: true
  workerd: true
packages:
  - "frontend"
  - "backend"
  - "shared"
