name = "urekoi-auth"
main = "src/index.tsx"
compatibility_date = "2026-09-06"

[[d1_databases]]
binding = "DB"
database_name = "urekoi-auth-db"
database_id = "434d564a-3d1d-4cdf-a15b-647b2c100b7f"
migrations_dir = "drizzle"
remote=true